# -*- coding: utf-8 -*-
"""ISTA_322_F22_HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqtBVr7EigSUXRdYaqMTnYNOxhk5OAUt

#HW3 - SQL
 
This homework has you working with a new database of information on ticket sales for various types of events.  Your job will be to do some initial exploring and then demonstrate your ability to do all the different types of SQL queries we learned over the last two week.  You'll also need to make one function that'll make looking at the tables easier. 
 
These questions are written in the way someone would ask them to you.  In other words, I'm using 'plain english' questions vs. ones where I'm very explicit in terms of what columns and tables to use.  Your exploring of the database and functions to ease that process will come in handy here!  
 
The database has been created using a set of data from Amazon. You can read more about what each table contains here: https://docs.aws.amazon.com/redshift/latest/dg/c_sampledb.html.

## Libraries and import functions

First bring the libraries we'll need!
"""

import psycopg2 
import pandas as pd

"""Now bring in all our functions we used in the lessons!  """

# Make our connection/cursor function 
AWS_host_name = "ticketsdb.chzr8692xwjt.us-east-2.rds.amazonaws.com"
AWS_dbname = "ticketsdb"
AWS_user_name = "postgres"
AWS_password = "ista322ticketsdb"

def get_conn_cur(): # define function name and arguments (there aren't any)
  # Make a connection
  conn = psycopg2.connect(
    host=AWS_host_name,
    database=AWS_dbname,
    user=AWS_user_name,
    password=AWS_password,
    port='5432')
  
  cur = conn.cursor()   # Make a cursor after

  return(conn, cur)   # Return both the connection and the cursor

# Same run_query function
def run_query(query_string):

  conn, cur = get_conn_cur() # get connection and cursor

  cur.execute(query_string) # executing string as before

  my_data = cur.fetchall() # fetch query data as before

  # here we're extracting the 0th element for each item in cur.description
  colnames = [desc[0] for desc in cur.description]

  cur.close() # close
  conn.close() # close

  return(colnames, my_data) # return column names AND data

# Column name function for checking out what's in a table
def get_column_names(table_name): # arguement of table_name
  conn, cur = get_conn_cur() # get connection and cursor

  # Now select column names while inserting the table name into the WERE
  column_name_query =  """SELECT column_name FROM information_schema.columns
       WHERE table_name = '%s' """ %table_name

  cur.execute(column_name_query) # exectue
  my_data = cur.fetchall() # store

  cur.close() # close
  conn.close() # close

  return(my_data) # return

# Check table_names
def get_table_names():
  conn, cur = get_conn_cur() # get connection and cursor

  # query to get table names
  table_name_query = """SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' """

  cur.execute(table_name_query) # execute
  my_data = cur.fetchall() # fetch results

  cur.close() #close cursor
  conn.close() # close connection

  return(my_data) # return your fetched results

"""## Make a SQL head function - 5 point

Make function to get the pandas equivalent of `.head()`

This function should be called `sql_head` and take a single argument of `table_name` where you specify the table name you want the head information from.  It should return the column names along with the first five rows of the table along.  

**For full points, return a pandas dataframe with this information so it displays nicely :)**
"""

# make sql_head function
def sql_head(table_name):
  # columns = get_column_names(table_name)
  limit = 5
  sql = f"select * from {table_name} limit {limit}"
  results = run_query(sql)
  columns = results[0]
  data = results[1]
  df = pd.DataFrame(columns=columns, data=data)
  return df

# Check that it works!
sql_head(table_name = 'sales')

"""## Explore and SELECT - 5 point

Let's start this homework with some basic queries to get a look at what's in the various tables.  I want you to do the following.

* Use your get_table_names() function to see what tables are in the database.
* Use your get_column_names() to get the column names of each of the tables.  **Do this all within a single cell to keep it neat**.
* Make and run a query that selects all columns from the event table.  Only return the first 5 rows.
* Use the `sql_head()` function you created to get the first five rows of the sales table.
"""

# Getting table names
table_info = []
table_names = get_table_names()
table_names

# Getting column names
table_info = []
for tn in table_names:
  columns = get_column_names(tn)
  table_info.append([tn, columns])

for row in table_info:
  print(row)

# Could also just use a list comprehension vs a bunch of print statements :)
names = get_table_names()
[get_column_names(table_name= x) for x in names]

# Query on events
sq = """select * from event limit 5"""
run_query(sq)

# Use sql_head to get the head of sales
sql_head("sales")

"""## WHERE - 5 points

Now let's do a bit of filtering with WHERE.  Write and run queries to get the following results.  
**LIMIT all returns to first five rows.**

* Get venues with >= 10000 seats from the venues table
* Get venues in Arizona
* Get users who have a first name that starts with H
* Get **just email addresses** of users who gave a .edu email address



"""

# Get big venues... so those with >= than 10000 seats
sq = """select * from venue where venueseats >= 10000"""
run_query(sq)

# Get venues in AZ
sq = """select * from venue where venuestate = 'AZ'"""
run_query(sq)

# Get users who have a first name that starts with H
sq = """select * from users where firstname like 'H%'"""
run_query(sq)

# Get all .edu email addresses... just the email addresses
sq = """select email from users where email like '%.edu'"""
run_query(sq)

"""## GROUP BY and HAVING - 5 points
 
Time to practice some GROUP BY and HAVING operations. Please write and run queries that do the following:
 
GROUP BY application
* Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
* Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months. Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'. 
* Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'. Also get their average commission made and alias as 'avg_com'.  Be sure to also display the seller_id.  
 
HAVING application
* Using the same query as the last one, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000.
* Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events. 
"""

### GROUP BY application
# Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
sql_head("event")
sq = """select venueid, count(venueid) as events_hosted from event group by venueid order by events_hosted desc limit 5"""
run_query(sq)

# Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months.
# Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'
sq = """select date_part('month', starttime) as month, count(eventid) as events_hosted from event group by month order by month asc"""
run_query(sq)

# Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'. 
# Also get their average commission made and alias as 'avg_com'. Be sure to also display the seller_id
sq = """select sellerid, sum(commission) as total_com, avg(commission) as avg_com from sales group by sellerid order by total_com desc limit 5"""
run_query(sq)

### HAVING application
# Using the same query as the last groupby, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000
sq = """select sellerid, sum(commission) as total_com, avg(commission) as avg_com from sales group by sellerid having sum(commission) > 4000 order by total_com desc"""
run_query(sq)

# Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events
sq = """select venueid from event group by venueid having count(venueid) > 60"""
run_query(sq)

"""## JOIN - 5 points
 
Time for some joins. You've probably noticed by now that there is at least one relational key in each table, but some have more.  For example, sales has a unique sale id, listing id, seller id, buyer id, date id.  This allows you to link each sale to relevant information in other tables.  
**LIMIT each output to 5**
 
Please write queries to do the following items:
 
* Join information of users to each sale made.  
* Join information about each venue to each event. 
"""

sq = """ SELECT * FROM sales
          LIMIT 5;"""
run_query(sq)

sq = """ SELECT * FROM users
          LIMIT 5;"""
run_query(sq)

get_column_names(table_name='users')

get_column_names(table_name='sales')

# Join users information to each sale
sq = """
select * from users
left join sales on sales.sellerid = users.userid
order by users.userid"""
run_query(sq)

# For each event attach the venue information
sq = """select * from event left join venue on venue.venueid = event.venueid order by event.venueid"""
run_query(sq)

"""## Subqueries - 5 points

To wrap up let's do several subqueries. Please do the following:

* Get all purchases made by users of live in Arizona
* Get event information for all events that took place in a venue where the venue name ends with 'Stadium'. 
* Get event information for all events where the total ticket sales were greater than $50,000.  
"""

# Get all purchases from users who live in Arizona
sq = """
select * from sales where sales.buyerid in (select userid from users where state in ('AZ'))
"""
run_query(sq)

# Get event information for all events that took place in a venue where the name ended in 'Stadium'
sq = """select * from event where event.venueid in (select venueid from venue where venuename like '%Stadium')"""
run_query(sq)

# Get event information where the total sales for that event were greater than $50000
sq = """select * from event where eventid in (select eventid from sales group by eventid having sum(pricepaid) > 50000)"""
run_query(sq)

get_table_names()

get_column_names(table_name= 'date')

sq = """ SELECT * FROM date
          LIMIT 5;"""
run_query(sq)